/*
 cSpell:ignore Publicacion Ubicacion
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens.Principal;

import Screens.Login.Login;
import Screens.Profile.PersonalProfile;
import javax.swing.JLabel;
import Code.CambiarIU;

import java.awt.Toolkit;
import java.util.Calendar;

/**
 *
 * @author tutaa
 */
public class Principal extends javax.swing.JFrame {

        /**
         * Creates new form Principal
         */
        public Principal() {
                initComponents();

                this.setTitle("Ingresar");
                this.setResizable(false);
                this.setLocationRelativeTo(null);

                this.setIconImage(Toolkit.getDefaultToolkit()
                                .getImage(getClass().getResource("/img/icon.png")));

        }

        public static String obtenerAño() {
                return String.valueOf(Calendar.getInstance().get(Calendar.YEAR));
        }

        public static void ponerTextoEtiqueta(JLabel label, String texto) {
                label.setText(texto);
        }

        public void crearLabel() {
                JLabel label = new JLabel("Hola mundo");

                label.setName("miJLabel");

                ventanaPrincipal.add(label);

                // Agregar el JPanel al JFrame
                this.add(ventanaPrincipal);

                // Hacer visible el JFrame
                this.setVisible(true);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                ventanaPrincipal = new javax.swing.JPanel();
                imgReload = new javax.swing.JLabel();
                panelMenu = new javax.swing.JPanel();
                imgCasa = new javax.swing.JLabel();
                imgVolver = new javax.swing.JLabel();
                imgUsuario = new javax.swing.JLabel();
                imgMenuBar = new javax.swing.JLabel();
                lbPonerUbicacion = new javax.swing.JLabel();
                lbPublicaciones = new javax.swing.JLabel();
                panelMapa = new javax.swing.JPanel();
                imgMarcador = new javax.swing.JLabel();
                imgMapa = new javax.swing.JLabel();
                scrollPublicaciones = new Screens.Principal.Custom.ScrollPaneWin11();
                panelPublicaciones = new javax.swing.JPanel();
                panelPublicacion = new javax.swing.JPanel();
                imgLike = new javax.swing.JLabel();
                lbPonerHoraIncidente = new javax.swing.JLabel();
                lbPonerUbicacionIncidente = new javax.swing.JLabel();
                lbPonerFechaIncidente = new javax.swing.JLabel();
                lbPonerTipoIncidente = new javax.swing.JLabel();
                lbPonerNombreUsuario = new javax.swing.JLabel();
                imgIconoPublicacion = new javax.swing.JLabel();
                imgPonerEvidenciaIncidente = new javax.swing.JLabel();
                imgFondoPub = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                ventanaPrincipal.setBackground(new java.awt.Color(22, 22, 26));
                ventanaPrincipal.setPreferredSize(new java.awt.Dimension(1080, 720));
                ventanaPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                imgReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reloadPequeño.png"))); // NOI18N
                imgReload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                ventanaPrincipal.add(imgReload, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 110, -1, -1));

                panelMenu.setBackground(new java.awt.Color(22, 22, 26));
                panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                imgCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/casaHover2.png"))); // NOI18N
                imgCasa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                panelMenu.add(imgCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

                imgVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
                imgVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                imgVolver.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                imgVolverMouseClicked(evt);
                        }

                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                imgVolverMouseEntered(evt);
                        }

                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                imgVolverMouseExited(evt);
                        }
                });
                panelMenu.add(imgVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

                imgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
                imgUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                imgUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                imgUsuarioMouseClicked(evt);
                        }

                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                imgUsuarioMouseEntered(evt);
                        }

                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                imgUsuarioMouseExited(evt);
                        }
                });
                panelMenu.add(imgUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

                imgMenuBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                imgMenuBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lineaVertical.png"))); // NOI18N
                imgMenuBar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                imgMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                imgMenuBarMouseEntered(evt);
                        }

                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                imgMenuBarMouseExited(evt);
                        }
                });
                panelMenu.add(imgMenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

                ventanaPrincipal.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, 60, 220));

                lbPonerUbicacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                lbPonerUbicacion.setForeground(new java.awt.Color(148, 161, 178));
                lbPonerUbicacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                lbPonerUbicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/marcador.png"))); // NOI18N
                lbPonerUbicacion.setText("Chía - Cundinamarca");
                ventanaPrincipal.add(lbPonerUbicacion,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, -1));

                lbPublicaciones.setFont(new java.awt.Font("Crabs", 1, 100)); // NOI18N
                lbPublicaciones.setForeground(new java.awt.Color(255, 255, 254));
                lbPublicaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbPublicaciones.setText("Publicaciones");
                ventanaPrincipal.add(lbPublicaciones,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1080, -1));

                panelMapa.setBackground(new java.awt.Color(22, 22, 26));
                panelMapa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                imgMarcador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/marcadorMapa.png"))); // NOI18N
                imgMarcador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                panelMapa.add(imgMarcador, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

                imgMapa.setBackground(new java.awt.Color(22, 22, 26));
                imgMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mapaColombia.png"))); // NOI18N
                panelMapa.add(imgMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 550));

                ventanaPrincipal.add(panelMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 420, 550));

                panelPublicaciones.setBackground(new java.awt.Color(36, 38, 41));
                panelPublicaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                panelPublicacion.setBackground(new java.awt.Color(36, 38, 41));
                panelPublicacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                imgLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/likeOff.png"))); // NOI18N
                imgLike.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                imgLike.setDisabledIcon(null);
                panelPublicacion.add(imgLike, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 30));

                lbPonerHoraIncidente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                lbPonerHoraIncidente.setForeground(new java.awt.Color(255, 255, 254));
                lbPonerHoraIncidente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbPonerHoraIncidente.setText("12:30 pm");
                panelPublicacion.add(lbPonerHoraIncidente,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, -1));

                lbPonerUbicacionIncidente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                lbPonerUbicacionIncidente.setForeground(new java.awt.Color(255, 255, 254));
                lbPonerUbicacionIncidente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                lbPonerUbicacionIncidente.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/img/marcadorPublicacion.png"))); // NOI18N
                lbPonerUbicacionIncidente.setText("Leticia - Amazonas");
                panelPublicacion.add(lbPonerUbicacionIncidente,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 270, -1));

                lbPonerFechaIncidente.setForeground(new java.awt.Color(255, 255, 254));
                lbPonerFechaIncidente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbPonerFechaIncidente.setText("11 - 05 -2024");
                panelPublicacion.add(lbPonerFechaIncidente,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, -1));

                lbPonerTipoIncidente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                lbPonerTipoIncidente.setForeground(new java.awt.Color(127, 90, 240));
                lbPonerTipoIncidente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbPonerTipoIncidente.setText("INCENDIO FORESTAL");
                panelPublicacion.add(lbPonerTipoIncidente,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 170, -1));

                lbPonerNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                lbPonerNombreUsuario.setForeground(new java.awt.Color(255, 255, 254));
                lbPonerNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbPonerNombreUsuario.setText("Miguel Angel Bejarano Muñoz");
                lbPonerNombreUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                panelPublicacion.add(lbPonerNombreUsuario,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 270, -1));

                imgIconoPublicacion.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/img/iconoPublicacion.png"))); // NOI18N
                panelPublicacion.add(imgIconoPublicacion,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

                imgPonerEvidenciaIncidente
                                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ejemploIncendio.jpg"))); // NOI18N
                imgPonerEvidenciaIncidente.setBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 90, 240)));
                panelPublicacion.add(imgPonerEvidenciaIncidente,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 90, 80));

                imgFondoPub.setBackground(new java.awt.Color(22, 22, 26));
                imgFondoPub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoPublicacion.png"))); // NOI18N
                panelPublicacion.add(imgFondoPub, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 180));

                panelPublicaciones.add(panelPublicacion,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 310, 200));

                scrollPublicaciones.setViewportView(panelPublicaciones);

                ventanaPrincipal.add(scrollPublicaciones,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 390, 520));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ventanaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ventanaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void imgMenuBarMouseExited(java.awt.event.MouseEvent evt) {
        }

        private void imgUsuarioMouseEntered(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgUsuario, "src/img/perfilHover2.png");

        }

        private void imgUsuarioMouseExited(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgUsuario, "src/img/usuario.png");

        }

        private void imgVolverMouseEntered(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgVolver, "src/img/volverHover2.png");

        }

        private void imgVolverMouseExited(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgVolver, "src/img/volver.png");
        }

        private void imgMenuBarMouseEntered(java.awt.event.MouseEvent evt) {
        }

        private void imgVolverMouseClicked(java.awt.event.MouseEvent evt) {

                Login login = new Login();
                login.setVisible(true);
                this.setVisible(false);
        }

        private void imgUsuarioMouseClicked(java.awt.event.MouseEvent evt) {
                PersonalProfile perfil = new PersonalProfile();
                perfil.setVisible(true);
                this.setVisible(false);
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(Principal.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(Principal.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(Principal.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(Principal.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> {
                        new Principal().setVisible(true);
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel imgCasa;
        private javax.swing.JLabel imgFondoPub;
        private javax.swing.JLabel imgIconoPublicacion;
        private javax.swing.JLabel imgLike;
        private javax.swing.JLabel imgMapa;
        private javax.swing.JLabel imgMarcador;
        private javax.swing.JLabel imgMenuBar;
        private javax.swing.JLabel imgPonerEvidenciaIncidente;
        private javax.swing.JLabel imgReload;
        private javax.swing.JLabel imgUsuario;
        private javax.swing.JLabel imgVolver;
        private javax.swing.JLabel lbPonerFechaIncidente;
        private javax.swing.JLabel lbPonerHoraIncidente;
        private javax.swing.JLabel lbPonerNombreUsuario;
        private javax.swing.JLabel lbPonerTipoIncidente;
        private javax.swing.JLabel lbPonerUbicacion;
        private javax.swing.JLabel lbPonerUbicacionIncidente;
        private javax.swing.JLabel lbPublicaciones;
        private javax.swing.JPanel panelMapa;
        private javax.swing.JPanel panelMenu;
        private javax.swing.JPanel panelPublicacion;
        private javax.swing.JPanel panelPublicaciones;
        private javax.swing.JScrollPane scrollPublicaciones;
        private javax.swing.JPanel ventanaPrincipal;
        // End of variables declaration//GEN-END:variables
}
