/*
 cSpell:ignore Ubicacion
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens.Principal.ViewIncident;

import java.awt.Toolkit;
import java.util.Calendar;
import javax.swing.JLabel;

/**
 *
 * @author tutaa
 */
public class ViewIncident extends javax.swing.JFrame {

        /**
         * Creates new form ViewIncident
         */
        public ViewIncident() {
                initComponents();

                this.setTitle("Incidente");
                this.setResizable(false);
                this.setLocationRelativeTo(null);

                this.setIconImage(Toolkit.getDefaultToolkit()
                                .getImage(getClass().getResource("/img/icon.png")));

        }

        public static String obtenerAño() {
                return String.valueOf(Calendar.getInstance().get(Calendar.YEAR));
        }

        public static void ponerTextoEtiqueta(JLabel label, String texto) {
                label.setText(texto);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                ventanaMostrarIncidente = new javax.swing.JPanel();
                lbPonerNombreUsuario = new javax.swing.JLabel();
                lbPonerLikes = new javax.swing.JLabel();
                lbPonerTipoIncidente = new javax.swing.JLabel();
                scrollInfoIncidente = new Screens.Principal.Custom.ScrollPaneWin11();
                txtMostrarInfoIncidente = new javax.swing.JTextArea();
                imgPonerEvidenciaIncidente = new javax.swing.JLabel();
                lbPonerFechaIncidente = new javax.swing.JLabel();
                lbPonerHoraIncidente = new javax.swing.JLabel();
                lbPonerUbicacionIncidente = new javax.swing.JLabel();
                btnSalir = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                ventanaMostrarIncidente.setBackground(new java.awt.Color(22, 22, 26));
                ventanaMostrarIncidente.setPreferredSize(new java.awt.Dimension(1080, 720));
                ventanaMostrarIncidente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbPonerNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
                lbPonerNombreUsuario.setForeground(new java.awt.Color(255, 255, 254));
                lbPonerNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbPonerNombreUsuario.setText("Miguel Angel Bejarano Muñoz");
                lbPonerNombreUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                ventanaMostrarIncidente.add(lbPonerNombreUsuario,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 570, -1));

                lbPonerLikes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                lbPonerLikes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbPonerLikes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/likeVerdeGrande.png"))); // NOI18N
                lbPonerLikes.setText("10");
                ventanaMostrarIncidente.add(lbPonerLikes,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 570, -1));

                lbPonerTipoIncidente.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
                lbPonerTipoIncidente.setForeground(new java.awt.Color(127, 90, 240));
                lbPonerTipoIncidente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbPonerTipoIncidente.setText("INCENDIO FORESTAL");
                ventanaMostrarIncidente.add(lbPonerTipoIncidente,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 570, -1));

                txtMostrarInfoIncidente.setEditable(false);
                txtMostrarInfoIncidente.setBackground(new java.awt.Color(22, 22, 26));
                txtMostrarInfoIncidente.setColumns(1);
                txtMostrarInfoIncidente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                txtMostrarInfoIncidente.setForeground(new java.awt.Color(148, 161, 178));
                txtMostrarInfoIncidente.setRows(3);
                txtMostrarInfoIncidente.setBorder(null);
                txtMostrarInfoIncidente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                txtMostrarInfoIncidente.setFocusable(false);
                scrollInfoIncidente.setViewportView(txtMostrarInfoIncidente);

                ventanaMostrarIncidente.add(scrollInfoIncidente,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 200, 140));

                imgPonerEvidenciaIncidente.setBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 90, 240)));
                ventanaMostrarIncidente.add(imgPonerEvidenciaIncidente,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 150, 140));

                lbPonerFechaIncidente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                lbPonerFechaIncidente.setForeground(new java.awt.Color(255, 255, 254));
                lbPonerFechaIncidente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbPonerFechaIncidente.setText("11 - 05 -2024");
                ventanaMostrarIncidente.add(lbPonerFechaIncidente,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 200, -1));

                lbPonerHoraIncidente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                lbPonerHoraIncidente.setForeground(new java.awt.Color(255, 255, 254));
                lbPonerHoraIncidente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbPonerHoraIncidente.setText("12:30 pm");
                ventanaMostrarIncidente.add(lbPonerHoraIncidente,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 120, -1));

                lbPonerUbicacionIncidente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                lbPonerUbicacionIncidente.setForeground(new java.awt.Color(255, 255, 254));
                lbPonerUbicacionIncidente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbPonerUbicacionIncidente
                                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/marcadorGrande.png"))); // NOI18N
                lbPonerUbicacionIncidente.setText("Leticia - Amazonas");
                ventanaMostrarIncidente.add(lbPonerUbicacionIncidente,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 570, -1));

                btnSalir.setBackground(new java.awt.Color(127, 90, 240));
                btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btnSalir.setForeground(new java.awt.Color(255, 255, 254));
                btnSalir.setText("Salir");
                btnSalir.setActionCommand("Ingresar");
                btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnSalir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSalirActionPerformed(evt);
                        }
                });
                ventanaMostrarIncidente.add(btnSalir,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ventanaMostrarIncidente,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 568,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(ventanaMostrarIncidente,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                477,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {
                this.setVisible(false);
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(ViewIncident.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(ViewIncident.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(ViewIncident.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(ViewIncident.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> {
                        new ViewIncident().setVisible(true);
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnSalir;
        private javax.swing.JLabel imgPonerEvidenciaIncidente;
        private javax.swing.JLabel lbPonerFechaIncidente;
        private javax.swing.JLabel lbPonerHoraIncidente;
        private javax.swing.JLabel lbPonerLikes;
        private javax.swing.JLabel lbPonerNombreUsuario;
        private javax.swing.JLabel lbPonerTipoIncidente;
        private javax.swing.JLabel lbPonerUbicacionIncidente;
        private javax.swing.JScrollPane scrollInfoIncidente;
        private javax.swing.JTextArea txtMostrarInfoIncidente;
        private javax.swing.JPanel ventanaMostrarIncidente;
        // End of variables declaration//GEN-END:variables
}
