/*
 cSpell:ignore Ubicacion
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens.Profile;

import java.awt.Toolkit;
import java.sql.SQLException;

import Code.Conexion;
import Screens.Custom.CambiarIU;
import Screens.Custom.ObtenerIU;
import Screens.Custom.ScrollPaneWin11;
import Screens.Login.Login;
import Screens.Principal.Principal;

/**
 *
 * @author tutaa
 */
public class PersonalProfile extends javax.swing.JFrame {

        /**
         * Creates new form PersonalProfile
         */
        public PersonalProfile() {
                initComponents();

                this.setTitle("Perfil Personal");
                this.setResizable(false);
                this.setLocationRelativeTo(null);

                this.setIconImage(Toolkit.getDefaultToolkit()
                                .getImage(getClass().getResource("/img/icon.png")));

                desactivarBotonGuardar();

                ponerInformacion();
                textosLabels();
        }

        private void textosLabels() {
                imgVolver.setToolTipText("Salir");
                imgCasa.setToolTipText("Pantalla Principal");
        }

        private void ponerInformacion() {
                try {
                        var datos = Conexion.seleccionar(String.format("SELECT * FROM usuarios where id_usuario = %d",
                                        Login.idUsuarioGuardar),
                                        new String[] { "nombre", "correo", "departamento", "ciudad", "edad",
                                                        "seguidores",
                                                        "biografia" });

                        CambiarIU.ponerTextoEtiqueta(lbPonerNombre, ((String) datos.get(0).get(0)));
                        CambiarIU.ponerTextoEtiqueta(lbPonerCorreo, ((String) datos.get(0).get(1)));
                        CambiarIU.ponerTextoEtiqueta(lbPonerUbicacion,
                                        (((String) datos.get(0).get(3)) + " - " + ((String) datos.get(0).get(2))));
                        CambiarIU.ponerTextoEtiqueta(lbPonerEdad, (datos.get(0).get(4) + " años"));
                        CambiarIU.ponerTextoEtiqueta(lbPonerSeguidores, (datos.get(0).get(5) + " Seguidores"));
                        CambiarIU.ponerTextoArea(txtMostrarBiografia, ((String) datos.get(0).get(6)));

                } catch (SQLException e) {
                        e.printStackTrace();
                }
        }

        private void desactivarBotonGuardar() {
                btnGuardarBiografia.setEnabled(!ObtenerIU.obtenerTextoPanel(tfCambiarBiografia)
                                .equals(ObtenerIU.obtenerTextoArea(txtMostrarBiografia))
                                && ObtenerIU.obtenerTextoPanel(tfCambiarBiografia).length() > 5);
        }

        private void actualizarBiografia() throws SQLException {
                var nuevaBiografia = ObtenerIU.obtenerTextoPanel(tfCambiarBiografia);
                Conexion.actualizar(String.format("UPDATE usuarios SET biografia = '%s' WHERE id_usuario = %d",
                                nuevaBiografia, Login.idUsuarioGuardar));
                ponerInformacion();
                CambiarIU.ponerTextoPanel(tfCambiarBiografia, "");
                desactivarBotonGuardar();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                ventanaProfile = new javax.swing.JPanel();
                panelMenu = new javax.swing.JPanel();
                imgCasa = new javax.swing.JLabel();
                imgVolver = new javax.swing.JLabel();
                imgUsuario = new javax.swing.JLabel();
                imgMenuBar = new javax.swing.JLabel();
                lbPonerSeguidores = new javax.swing.JLabel();
                lbPonerUbicacion = new javax.swing.JLabel();
                lbPerfil = new javax.swing.JLabel();
                lbPonerNombre = new javax.swing.JLabel();
                lbPonerEdad = new javax.swing.JLabel();
                lbPonerCorreo = new javax.swing.JLabel();
                lbBiografía = new javax.swing.JLabel();
                scrollPonerBiografia = new ScrollPaneWin11();
                txtMostrarBiografia = new javax.swing.JTextArea();
                lbCambiarBiografia = new javax.swing.JLabel();
                scrollCambiarBiografia = new ScrollPaneWin11();
                tfCambiarBiografia = new javax.swing.JTextPane();
                btnGuardarBiografia = new javax.swing.JButton();
                btnCancelarBiografia = new javax.swing.JButton();
                imgFondo = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                ventanaProfile.setBackground(new java.awt.Color(22, 22, 26));
                ventanaProfile.setPreferredSize(new java.awt.Dimension(1080, 720));
                ventanaProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                panelMenu.setBackground(new java.awt.Color(22, 22, 26));
                panelMenu.setOpaque(false);
                panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                imgCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/casa.png"))); // NOI18N
                imgCasa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                imgCasa.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                imgCasaMouseClicked(evt);
                        }

                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                imgCasaMouseEntered(evt);
                        }

                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                imgCasaMouseExited(evt);
                        }
                });
                panelMenu.add(imgCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

                imgVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
                imgVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                imgVolver.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                imgVolverMouseClicked(evt);
                        }

                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                imgVolverMouseEntered(evt);
                        }

                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                imgVolverMouseExited(evt);
                        }
                });
                panelMenu.add(imgVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

                imgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/perfilHover2.png"))); // NOI18N
                imgUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                panelMenu.add(imgUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

                imgMenuBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                imgMenuBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lineaVertical.png"))); // NOI18N
                imgMenuBar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                panelMenu.add(imgMenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

                ventanaProfile.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, 60, 220));

                lbPonerSeguidores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                lbPonerSeguidores.setForeground(new java.awt.Color(148, 161, 178));
                lbPonerSeguidores.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                lbPonerSeguidores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seguidores.png"))); // NOI18N
                lbPonerSeguidores.setText("-");
                ventanaProfile.add(lbPonerSeguidores,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 160, -1));

                lbPonerUbicacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                lbPonerUbicacion.setForeground(new java.awt.Color(148, 161, 178));
                lbPonerUbicacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                lbPonerUbicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/marcador.png"))); // NOI18N
                lbPonerUbicacion.setText("-");
                lbPonerUbicacion.setToolTipText("");
                ventanaProfile.add(lbPonerUbicacion,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, -1));

                lbPerfil.setFont(new java.awt.Font("Crabs", 1, 100)); // NOI18N
                lbPerfil.setForeground(new java.awt.Color(255, 255, 254));
                lbPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbPerfil.setText("Perfil");
                ventanaProfile.add(lbPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1080, -1));

                lbPonerNombre.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
                lbPonerNombre.setForeground(new java.awt.Color(148, 161, 178));
                lbPonerNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbPonerNombre.setText("-");
                lbPonerNombre.setToolTipText("");
                ventanaProfile.add(lbPonerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1080, -1));

                lbPonerEdad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                lbPonerEdad.setForeground(new java.awt.Color(148, 161, 178));
                lbPonerEdad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbPonerEdad.setText("-");
                ventanaProfile.add(lbPonerEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1080, -1));

                lbPonerCorreo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                lbPonerCorreo.setForeground(new java.awt.Color(148, 161, 178));
                lbPonerCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbPonerCorreo.setText("-");
                ventanaProfile.add(lbPonerCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1080, -1));

                lbBiografía.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                lbBiografía.setForeground(new java.awt.Color(255, 255, 254));
                lbBiografía.setText("BIOGRAFÍA: ");
                ventanaProfile.add(lbBiografía, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

                scrollPonerBiografia.setBackground(new java.awt.Color(0, 2, 2));

                txtMostrarBiografia.setEditable(false);
                txtMostrarBiografia.setBackground(new java.awt.Color(0, 2, 2));
                txtMostrarBiografia.setColumns(1);
                txtMostrarBiografia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                txtMostrarBiografia.setForeground(new java.awt.Color(148, 161, 178));
                txtMostrarBiografia.setLineWrap(true);
                txtMostrarBiografia.setRows(3);
                txtMostrarBiografia.setWrapStyleWord(true);
                txtMostrarBiografia.setBorder(null);
                txtMostrarBiografia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                txtMostrarBiografia.setFocusable(false);
                scrollPonerBiografia.setViewportView(txtMostrarBiografia);

                ventanaProfile.add(scrollPonerBiografia,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 380, 100));

                lbCambiarBiografia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                lbCambiarBiografia.setForeground(new java.awt.Color(255, 255, 254));
                lbCambiarBiografia.setText("CAMBIAR BIOGRAFÍA: ");
                ventanaProfile.add(lbCambiarBiografia,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, -1));

                scrollCambiarBiografia.setBackground(new java.awt.Color(0, 2, 2));

                tfCambiarBiografia.setBackground(new java.awt.Color(0, 2, 2));
                tfCambiarBiografia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                tfCambiarBiografia.setForeground(new java.awt.Color(148, 161, 178));
                tfCambiarBiografia.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfCambiarBiografiaKeyReleased(evt);
                        }
                });
                scrollCambiarBiografia.setViewportView(tfCambiarBiografia);

                ventanaProfile.add(scrollCambiarBiografia,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 380, 80));

                btnGuardarBiografia.setBackground(new java.awt.Color(127, 90, 240));
                btnGuardarBiografia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btnGuardarBiografia.setForeground(new java.awt.Color(255, 255, 254));
                btnGuardarBiografia.setText("Guardar");
                btnGuardarBiografia.setActionCommand("Ingresar");
                btnGuardarBiografia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnGuardarBiografia.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                try {
                                        btnGuardarBiografiaActionPerformed(evt);
                                } catch (SQLException e) {
                                        e.printStackTrace();
                                }
                        }
                });
                ventanaProfile.add(btnGuardarBiografia,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 650, -1, -1));

                btnCancelarBiografia.setBackground(new java.awt.Color(127, 90, 240));
                btnCancelarBiografia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btnCancelarBiografia.setForeground(new java.awt.Color(255, 255, 254));
                btnCancelarBiografia.setText("Cancelar");
                btnCancelarBiografia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnCancelarBiografia.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCancelarBiografiaActionPerformed(evt);
                        }
                });
                ventanaProfile.add(btnCancelarBiografia,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, -1, -1));

                imgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
                imgFondo.setText("jLabel1");
                ventanaProfile.add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ventanaProfile, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ventanaProfile, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void imgVolverMouseClicked(java.awt.event.MouseEvent evt) {
                Login login = new Login();
                login.setVisible(true);
                this.setVisible(false);
        }

        private void imgVolverMouseEntered(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgVolver, "src/img/volverHover2.png");
        }

        private void imgVolverMouseExited(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgVolver, "src/img/volver.png");
        }

        private void imgCasaMouseClicked(java.awt.event.MouseEvent evt) {
                Principal principal = new Principal();
                principal.setVisible(true);
                this.setVisible(false);
        }

        private void imgCasaMouseEntered(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgCasa, "src/img/casaHover2.png");
        }

        private void imgCasaMouseExited(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgCasa, "src/img/casa.png");
        }

        private void btnGuardarBiografiaActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
                try {
                        actualizarBiografia();
                } catch (Exception e) {
                        System.out.println("Error:" + e);
                }
        }

        private void btnCancelarBiografiaActionPerformed(java.awt.event.ActionEvent evt) {
                CambiarIU.ponerTextoPanel(tfCambiarBiografia, "");
                btnGuardarBiografia.setEnabled(false);
        }

        private void tfCambiarBiografiaKeyReleased(java.awt.event.KeyEvent evt) {
                desactivarBotonGuardar();
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(PersonalProfile.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(PersonalProfile.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(PersonalProfile.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(PersonalProfile.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> {
                        new PersonalProfile().setVisible(true);
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCancelarBiografia;
        private javax.swing.JButton btnGuardarBiografia;
        private javax.swing.JLabel imgCasa;
        private javax.swing.JLabel imgFondo;
        private javax.swing.JLabel imgMenuBar;
        private javax.swing.JLabel imgUsuario;
        private javax.swing.JLabel imgVolver;
        private javax.swing.JLabel lbBiografía;
        private javax.swing.JLabel lbCambiarBiografia;
        private javax.swing.JLabel lbPerfil;
        private javax.swing.JLabel lbPonerCorreo;
        private javax.swing.JLabel lbPonerEdad;
        private javax.swing.JLabel lbPonerNombre;
        private javax.swing.JLabel lbPonerSeguidores;
        private javax.swing.JLabel lbPonerUbicacion;
        private javax.swing.JPanel panelMenu;
        private javax.swing.JScrollPane scrollCambiarBiografia;
        private javax.swing.JScrollPane scrollPonerBiografia;
        private javax.swing.JTextPane tfCambiarBiografia;
        private javax.swing.JTextArea txtMostrarBiografia;
        private javax.swing.JPanel ventanaProfile;
        // End of variables declaration//GEN-END:variables
}
